name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '7.x'

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install docfx
        run: dotnet tool update -g docfx

      - name: Generate doc
        run: docfx docfx.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: gh-pages
          cname: sccg.ryota2357.com